# Generated by Django 5.2.12 on 2026-04-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_sitesettings_withdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin approval required before buyers can see'),
        ),
    ]
