# Generated by Django 5.2.12 on 2026-04-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_content_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='zip_file',
            field=models.FileField(blank=True, help_text='Upload a ZIP file containing all videos', null=True, upload_to='content_zips/'),
        ),
    ]
